### ISSUE TITLE
How to set sandbox="allow-downloads"?

### ISSUE THREAD

**Issue by vennsoh** [P5-wrapper/react#60] opened 2020-11-12 13:26 UTC
I've created a prototype that allows the user to download a file to their local machine once they're done with manipulation.
Essentially I'm trying to re-create this by going through this tutorial in React https://www.youtube.com/watch?v=JWsKay58Z2g&list=PLRqwX-V7Uu6YPSwT06y_AEYTqIwbeam3y&index=12

However in Chrome I'm getting this error saying...
`Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.`

After Google, it seems this is something new they just released. However we can opt in.
I wonder if anyone know how to set `allow-downloads` in my sandbox attribute?

**Comment by jamesrweb** [comment] 2020-11-14 22:53
Wherever you are running your code is using an `iframe` somewhere it would seem. For more info see the [iframe specification regarding the sandbox attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox). You can also try running the code in another browser but it could also be the case that the issue is with content security policy (CSP) which would make that a mute point. Although in saying that, it doesn't seem like it since you would get an error for `allow-downloads-without-user-activation` instead of the `allow-downloads` error. Still, it might be worth [checking that potential case out](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/sandbox) here.

As this isn't an issue with the react-p5-wrapper library however, I will now close the issue.

**Closed as completed** 2020-11-14 22:54 UTC

**Comment by vennsoh** [comment] 2020-11-14 22:58
Thanks for the clarification @jamesrweb yup not a problem with the react p5 wrapper but I figured it's with another tool I'm using with.

**Comment by jamesrweb** [comment] 2020-11-14 22:59
@vennsoh Updated my last comment with more tips for you to check out. Hope things are working now or soon, if there is anything for this library I can help with, just let us know in a follow-up issue.
